version: '3.8'

services:
  postgres_db_testik:
    image: postgres:latest
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_DB=testik
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '127.0.0.1:5432:5433'
    volumes:
      - postgres_db_testik:/var/lib/postgresql/data/pgdata

volumes:
  postgres_db_testik:
