"""2

Revision ID: 61b8b68fd8d5
Revises: d95afbc1cf89
Create Date: 2024-08-21 02:14:29.877112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b8b68fd8d5'
down_revision: Union[str, None] = 'd95afbc1cf89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('carts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True, comment='Name'),
    sa.PrimaryKeyConstraint('id'),
    comment='Carts'
    )
    op.create_table('carts_products',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False, comment='some some'),
    sa.Column('cart_id', sa.BIGINT(), nullable=False, comment='some some'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Relationship between cart and products'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts_products')
    op.drop_table('carts')
    # ### end Alembic commands ###
