"""1

Revision ID: d95afbc1cf89
Revises: 
Create Date: 2024-08-21 00:10:27.343093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95afbc1cf89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True, comment='Product Name'),
    sa.Column('price', sa.Float(), nullable=True, comment='Price'),
    sa.PrimaryKeyConstraint('id'),
    comment='Products'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
